### ISSUE TITLE
Add Deep learning

### ISSUE THREAD

**Issue by csawtelle** [csawtelle/mlhq.io#266]
https://github.com/gerardramosm89/mscsblog/issues/67

**Comment by gerardramosm89** [comment]
@csawtelle This is a brand new `Path` right and not one of the `Sub-Path`'s that we are adding?

**Comment by csawtelle** [comment]
Yesl, PATH

**Comment by csawtelle** [comment]
https://github.com/gerardramosm89/mscsblog/commit/f97e8f9c26f0a2b78df5f575f10db80b0518ac0d
