### ISSUE TITLE
Finish "Edit" page

### ISSUE THREAD

**Issue by csawtelle** [csawtelle/mlhq.io#274]
https://github.com/gerardramosm89/mscsblog/issues/3

**Comment by csawtelle** [comment]
Edit page is missing options:

![image](https://user-images.githubusercontent.com/12061655/34959537-cb1dd414-f9eb-11e7-8f37-9ce11f86bfc4.png)

**Comment by gerardramosm89** [comment]
ah i see. @csawtelle so it looks like if you ever **edit** and **leave one of the fields empty** and then save, it breaks.

is this the behavior you ran into?

**Comment by gerardramosm89** [comment]
looks like it saves but none of the components are set to handle any empty fields on load, such as pre-loading the contents of the post when you try to edit or just viewing a post in general

**Comment by gerardramosm89** [comment]
This should be good now. No edits will be allowed unless all the fields have content.
