### ISSUE TITLE
Show subscription status in dashboard

### ISSUE THREAD

**Issue by csawtelle** [csawtelle/mlhq.io#278]

**Comment by gerardramosm89** [comment]
Thanks for maintaining these, I need these tickets to help manage my focus 🙃

**Comment by sbaby171** [comment]
Hey guy, quick suggestion.

The main page looks amazing (the visuals look dope) but i think the status
bar should follow as user scrolls down the page?

What are you thoughts on this??

-MS

**Comment by gerardramosm89** [comment]
oh the `navbar` on top right? as you scroll down have it `fixed`? this was something that we did want before. and is definitely doable. let's have our PM @csawtelle put it in the sprint if this is wanted.

I would be fine with it once we actually have some nav items to put on there.

**Comment by csawtelle** [comment]
sprint 3 is getting  pretty heavy, lets push it off for now but I made an issue to track it https://github.com/csawtelle/mlhq.io/issues/282
