### ISSUE TITLE
"Computational Science" section

### ISSUE THREAD

**Issue by csawtelle** [csawtelle/mlhq.io#279]
Max would like to start contributing to the MLHQ under the learning path "Computational Science"

**Comment by gerardramosm89** [comment]
nice I'm happy to see this

**Comment by sbaby171** [comment]
:)

**Comment by gerardramosm89** [comment]
done. closing

**Comment by csawtelle** [comment]
2bf400ed5e39099cf3e433c4f11bb754b95ecf29
