### ISSUE TITLE
Front page load efficiency, should shoot for sub 500ms

### ISSUE THREAD

**Issue by csawtelle** [csawtelle/mlhq.io#280]
The front page loads really slowly, not sure what is causing it 
![image](https://user-images.githubusercontent.com/12061655/35165312-b13c4c5a-fd02-11e7-9afd-e4af31baa2b9.png)

**Comment by gerardramosm89** [comment]
I have noticed this as well and I have an idea for the cause and fix, I'll put this into sprint 3

**Comment by gerardramosm89** [comment]
![screen shot 2018-01-19 at 4 42 53 pm](https://user-images.githubusercontent.com/22526582/35177813-d5805be4-fd37-11e7-8966-c92ffb6dfcc0.png)

@csawtelle sub 500ms confirmed

**Comment by gerardramosm89** [comment]
done

**Comment by csawtelle** [comment]
https://github.com/gerardramosm89/mscsblog/commit/54858dce64a00c3ddf8dbfe3b107ad3b959104b9
