### ISSUE TITLE
Need descriptions for the new topics

### ISSUE THREAD

**Issue by gerardramosm89** [csawtelle/mlhq.io#281]

**Comment by gerardramosm89** [comment]
![screen shot 2018-01-19 at 4 56 46 pm](https://user-images.githubusercontent.com/22526582/35178018-c3e914e6-fd39-11e7-9f2b-ed64402c684a.png)

right now these three share the same description, can we get new subheading for these that I can put in?

and same for `Computational Science`, let's have a paragraph for the subheading I can add before putting it in

**Comment by csawtelle** [comment]
Deep Learning: Practical application of machine learning using neural networks, simulating neural responses to understand and process complex data representations.

Computational Science: Understand the methods with which computer simulations are used to map, model, and solve natural systems spanning many scientific disciplines.

**Comment by gerardramosm89** [comment]
@csawtelle what about **Natural Language Processing**

**Comment by csawtelle** [comment]
@gerardramosm89 edited
